name: Sync Sub-Development with Deployment

on:
  repository_dispatch:
    types:
      - deploy

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sub-Development Repository
      uses: actions/checkout@v3

    - name: Push Changes to Deployment Repository
      run: |
        # Add subtree with squash
        git subtree add --prefix=srdvvv https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git --squash

        # Push subtree to stage branch in the deployment repository
        git subtree pull --prefix=srdvvv https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git stage --squash

        # Push subtree to stage branch in the deployment repository again (if needed)
        git subtree push --prefix=srdvvv https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git stage
