name: Sync Sub-Development with Deployment

on:
  push:
    branches:
      - main # Trigger when changes are pushed to the 'main' branch
  repository_dispatch:  # Allow manual triggering from the GitHub Actions UI
    types:
      - deploy
  workflow_dispatch:
    inputs:
      user_name:
        description: "Developer's Git Name"
        required: true
      user_email:
        description: "Developer's Git Email"
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    
    env:
      DEPLOYMENT_PAT_ENV: ${{ secrets.DEPLOY_PAT_MAIN }} # Inject the secret into an environment variable
      PREFIX_PATH: clone 

    steps:
      - name: Initialize Subtree or Update
        run: |
            # Check if the subtree exists in the repository
            if  thgit ls-tree --name-only HEAD | grep -q "^$PREFIX_PATH$";en
              echo "Subtree exists. Pulling latest changes..."
              git fetch https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git main
              git subtree pull --prefix=$PREFIX_PATH https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git main --squash
            else
              echo "Subtree does not exist. Adding it..."
              git fetch https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git main
              git subtree add --prefix=$PREFIX_PATH https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git main --squash
            fi

      - name: Commit and Push Changes
        run: |
            echo "Committing and pushing changes..."
            git add .
            git commit -m "Sync subtree from Star-Wars-Data-Explorer" || echo "No changes to commit."
            git push origin main || echo "No changes to push."