name: Sync Sub-Development with Deployment

on:
  push:
    branches:
      - main # Replace 'main' with the branch you want to monitor

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sub-Development Repository
      uses: actions/checkout@v3

    - name: Push Changes to Deployment Repository
      run: |
        git remote add deployment https://mjsol12:${{ secrets.DEPLOYMENT_PAT }}@github.com/mjsol12/Star-Wars-Data-Explorer.git
        git subtree push --prefix=src deployment main
