name: Sync Sub-Development with Deployment

on:
  push:
    branches:
      - main # Trigger when changes are pushed to the 'main' branch
  repository_dispatch:  # Allow manual triggering from the GitHub Actions UI
    types:
      - deploy
  workflow_dispatch:
    inputs:
      user_name:
        description: "Developer's Git Name"
        required: true
      user_email:
        description: "Developer's Git Email"
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

    env:
      DEPLOYMENT_PAT_ENV: ${{ secrets.DEPLOY_PAT_MAIN }} # Inject the secret into an environment variable
      PREFIX_PATH: clone 


  release:
      runs-on: ubuntu-latest
      needs: checkout
      steps:
        - name: Release
          uses: xedi/action-subtree-sync@1.0.0
          with:
            subtree: 'Star-Wars-Data-Explorer'
            subtree_deploy_key: ${{ secrets.DEPLOY_PAT_MAIN }}
            split_prefix: 'src/directory'