name: Sync Sub-Development with Deployment

on:
  push:
    branches:
      - main # Trigger when changes are pushed to the 'main' branch
  repository_dispatch:  # Allow manual triggering from the GitHub Actions UI
    types:
      - deploy
  workflow_dispatch:
    inputs:
      user_name:
        description: "Developer's Git Name"
        required: true
      user_email:
        description: "Developer's Git Email"
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    
    env:
      DEPLOYMENT_PAT_ENV: ${{ secrets.DEPLOY_PAT_MAIN }} # Inject the secret into an environment variable
      PREFIX_PATH: clone 


    steps:
    - name: Checkout Sub-Development Repository
      uses: actions/checkout@v3

    - name: Configure Git Identity
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Add Subtree Changes
      run: |
        echo "Adding subtree or pulling changes..."
        git subtree add --prefix=$PREFIX_PATH https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git --squash

    - name: Pull Subtree Changes
      run: |
        echo "Adding subtree or pulling changes..."
        git subtree pull --prefix=$PREFIX_PATH https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git stage --squash

    - name: Push Changes
      run: |
        # Push subtree to stage branch in the deployment repository again (if needed)
        git push
