name: Sync Sub-Development with Deployment

on:
  repository_dispatch:
    types:
      - deploy

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sub-Development Repository
      uses: actions/checkout@v3

    - name: Push Changes to Deployment Repository
      run: |
        git subtree add --prefix=srdvvv https://mjsol12:${{ secrets.DEPLOYMENT_PAT }}@github.com/mjsol12/Star-Wars-Data-Explorer.git --squash
        git subtree push --prefix=srdvvv https://mjsol12:${{ secrets.DEPLOYMENT_PAT }}@github.com/mjsol12/Star-Wars-Data-Explorer.git stage --squash
        git subtree push --prefix=srdvvv https://mjsol12:${{ secrets.DEPLOYMENT_PAT }}@github.com/mjsol12/Star-Wars-Data-Explorer.git stage
