name: Sync Sub-Development with Deployment

on:
  push:
    branches:
      - main # Trigger when changes are pushed to the 'main' branch
  repository_dispatch:  # Allow manual triggering from the GitHub Actions UI
    types:
      - deploy
  workflow_dispatch:
    inputs:
      user_name:
        description: "Developer's Git Name"
        required: true
      user_email:
        description: "Developer's Git Email"
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    
    env:
      DEPLOYMENT_PAT_ENV: ${{ secrets.DEPLOY_PAT_MAIN }} # Inject the secret into an environment variable


    steps:
    - name: Checkout Sub-Development Repository
      uses: actions/checkout@v3

    - name: Configure Git Identity
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Conditionally Add or Update Subtree
      run: |
        if git ls-tree --name-only HEAD | grep -q '^srdvvv$'; then
          echo "Directory 'srdvvv' already exists. Skipping subtree add."
           # Push subtree to stage branch in the deployment repository
           git subtree pull --prefix=srdvvv https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git stage --squash
        else
          echo "Directory 'srdvvv' does not exist. Adding subtree."
          git subtree add --prefix=srdvvv https://mjsol12:${{ secrets.DEPLOYMENT_PAT }}@github.com/mjsol12/Star-Wars-Data-Explorer.git --squash
        fi

    - name: Push Changes to Deployment Repository
      run: |
        # Push subtree to stage branch in the deployment repository again (if needed)
        git push
