name: Sync Sub-Development with Deployment

on:
  push:
    branches:
      - main # Trigger when changes are pushed to the 'main' branch
  repository_dispatch:  # Allow manual triggering from the GitHub Actions UI
    types:
      - deploy
  workflow_dispatch:
    inputs:
      user_name:
        description: "Developer's Git Name"
        required: true
      user_email:
        description: "Developer's Git Email"
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    
    env:
      DEPLOYMENT_PAT_ENV: ${{ secrets.DEPLOY_PAT_MAIN }} # Inject the secret into an environment variable
      PREFIX_PATH: clone 


    steps:
    - name: Checkout Sub-Development Repository
      uses: actions/checkout@v3

    - name: Configure Git Identity
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
    
    - name: Clean Subtree Directory
      run: |
          if [ -d "$PREFIX_PATH" ]; then
            echo "Directory $PREFIX_PATH exists. Removing it..."
            git rm -r --cached $PREFIX_PATH
            rm -rf $PREFIX_PATH
          else
            echo "Directory $PREFIX_PATH does not exist. Proceeding with subtree add."
          fi
  
    - name: Add Subtree
      run: |
          echo "Adding subtree..."
          git fetch https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git main
          git subtree add --prefix=$PREFIX_PATH https://mjsol12:$DEPLOYMENT_PAT_ENV@github.com/mjsol12/Star-Wars-Data-Explorer.git main --squash
  
    - name: Commit and Push Changes
      run: |
          echo "Committing and pushing changes..."
          git add .
          git commit -m "Sync subtree from Star-Wars-Data-Explorer" || echo "No changes to commit."
          git push origin main || echo "No changes to push."